### ISSUE TITLE
ngx-translate is not always working with ng-bootstrap accordion

### ISSUE THREAD

**Issue by Bukic** [ngx-formly/ngx-formly#2214]
**Description**
When using ngx-translate with accordion content inside accordion is not always translated when changing language. 

**Minimal Reproduction**

Just open the stackblitz example. Change default language and expand accordion label and placeholders won't be translate. Actually sometimes they are translated sometimes not.. Just play with dropdown change and expanded/collapsed state of accordiion.

https://stackblitz.com/edit/angular-6pupmw

**Your Environment**

- Angular version: 9.1.3
- Formly version: 5.6.0

**Additional context**

**Comment by Bukic** [comment]
@aitboudad  I see you pushed fix for this, thanks! I have one more question. I want to translate validation messages instead of hard code strings. Currently I have separate file validation.messages.ts where i add my custom messages and just register them in validationMessages array. How can i translate content in those messages? Can I reuse translate.extension.ts file somehow or? Stackblitz is updated: 

https://stackblitz.com/edit/angular-6pupmw

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.6.1](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.6.1) release.

There is one limitation to the tab label where it should be translated inside `AccordionFieldComponent` type: https://stackblitz.com/edit/angular-6pupmw

**Comment by aitboudad** [comment]
> I want to translate validation messages instead of hard code strings. 

check:
- https://github.com/ngx-formly/ngx-formly/issues/2140#issuecomment-598253799
- https://github.com/ngx-formly/ngx-formly/issues/2140#issuecomment-598268027

**Comment by Bukic** [comment]
@aitboudad  I succeed with validationLoader. But one more question, sorry. I am using dynamic module where i create custom types, validation messages.. etc.. and then just import that module. But what i need is to 'combine' en.json files from dynamic module and from module for example when i am using this dynamic formly module. I have translate loader in dynamic module:

`export function HttpLoaderFactory(httpClient: HttpClient) {
    return new TranslateHttpLoader(httpClient, './assets/i18n/', '.json');
}`

and en.json file in assets/i18n in this module. 

But also in another module  i have en.json file in assets/i18n and with current code only from second module en.json file is loaded.

**Comment by Bukic** [comment]
@aitboudad  I updated to 5.6.1 but it seems like it is not fixed... Again if i change language from dropdown, expand accordion translation is again not updated with chosen language. But now strange things happen also.. like for example  if i collapse accordion translation is changed back to previous chosen dropdown language...

**Comment by aitboudad** [comment]
>  I updated to 5.6.1 but it seems like it is not fixed..

Your `stackblitz` is not updated, just make sure to take account of the limitation mentioned in the comment above.


> Also one more thing about validation messages. I succeed to implement with validation loader. But if message is shown and i change language message is not translated with newly chosen language.

Could you please include the code in your stackblitz in order to fix both issues at once.

**Comment by Bukic** [comment]
@aitboudad Can you please check the stackblitz now:

https://stackblitz.com/edit/angular-6pupmw

Issue 1: Just focus test input and leave it empty. This field is required message will be shown. Change language to 'fr'. Message is not translate to 'fr' it is still in 'en'.

Issue 2: I added | translate to ngb-panel tab itself. But there are still issues. Do this: expand accordion and change language to 'fr'. Everything is translated fine (sometimes not...). Now collapse accordion and change language to 'en'. Main accordion label is not translate it is still in 'fr'. 

Let me know if you need some more clarification. Thanks!!!

**Comment by aitboudad** [comment]
Issue 1: I'll try to find a solution when time allows :pray:!

Issue 2: for the Main accordion, the translation should be done in the component template instead of extension:

skip translate for the accordion label and use `translate` pipe:

```html
<ngb-panel [title]="tab.templateOptions.title|translate">
```

**Comment by Bukic** [comment]
Thanks for speedy response @aitboudad !!! Looking forward for issue 1 solution 👍 

Btw does this mean that for custom components that are more complex like accordion or maybe tabs we should use translate pipe instead of translate extension? Thanks!

**Comment by aitboudad** [comment]
> Btw does this mean that for custom components that are more complex like accordion or maybe tabs we should use translate pipe instead of translate extension?

When the accordion is collapsed, the fields inside accordion is destroyed which means unsubscription from the translate stream, so the solution is either to use  translate pipe for the accordion tab or rely on the parent field to get the label of each tab instead something like:

```ts
{
  type: 'ac-accordion-field',
  templateOptions: {
  	tabs: ['HOME.accordionParticipant']
  },
  fieldGroupClassName: 'row',
  fieldGroup: [...]
}
```

**Comment by Bukic** [comment]
@aitboudad  got you. But for second approach i will need to add some condition in translate.extension.ts to check for this scenario... cause currently only  label and placeholders which are in templateOptions are translate. I think pipe translate will do for now :)

**Comment by aitboudad** [comment]
it'll be part of `v5.7` release, I'll let you know once done (most probably will be released on Monday).

**Comment by aitboudad** [comment]
@Bukic `v5.7` is released which resolve the validation message issue, I've added an example in https://formly.dev/examples/advanced/i18n-alternative:

The `ValidationLoader` is not needed anymore and can be removed.

```patch
export function registerTranslateExtension(translate: TranslateService) {
  return {
+   validationMessages: [
+     {
+       name: 'required',
+       message() {
+         return translate.stream('FORM.VALIDATION.REQUIRED');
+       },
+     },
+   ],
    extensions: [{
      name: 'translate',
      extension: new TranslateExtension(translate)
    }],
  };
}
```

**Comment by Bukic** [comment]
Hey @aitboudad updated to 5.7.0 it seems to be working now!! Thanks! :) 

One question. As you mention ValidationLoader can be removed now. I still want to keep my messages in separate validation.messages.ts file. How can i call them in validationMessages extension? For example:

validation.messages.ts file
`
export function requiredValidationMessage(translate) {
    return translate.stream('validations.required');
}
`
form.extension.ts file

`
export function registerFormExtension(translate: TranslateService) {
    return {
        extensions: [
            {
                name: 'translate',
                extension: new TranslateExtension(translate),
            },
        ],
        validationMessages: [
           // this works
            {
                name: 'required',
                message():  return translate.stream('validations.required');
            },
           // this does not work
            {
                name: 'required',
                message:  requiredValidationMessage
            },
        ],
    };
}
`

**Comment by aitboudad** [comment]
```patch
export function requiredValidationMessage(translate) {
-    return translate.stream('validations.required');
+    return () => translate.stream('validations.required');
}
```

```patch
        validationMessages: [
            {
                name: 'required',
-                message:  requiredValidationMessage
+                message:  requiredValidationMessage(translate)
            },
        ],
```

**Comment by Bukic** [comment]
Yeah i asked  the question in wrong way...  This will work and 

```
return (err, field) => translate.stream('validations.required');
```

still returns me err and field itself so all good 👍
