### ISSUE TITLE
Json schema:  if array type is empty , how to set model null

### ISSUE THREAD

**Issue by linfanxxxx** [ngx-formly/ngx-formly#2806]
**Question**

when array field is empty , just like [] . how can i set the model null, instead of [];

![image](https://user-images.githubusercontent.com/34636576/115333463-43edf280-a1cc-11eb-8c3e-9b4ffdb01077.png)

![image](https://user-images.githubusercontent.com/34636576/115333491-549e6880-a1cc-11eb-94f7-8457132245ed.png)

example:

https://stackblitz.com/edit/angular-92wxm5?file=src%2Fapp%2Fapp.component.html

**Comment by kenisteward** [comment]
This should be fixed as of latest version ( alpha 6 ) please try installing
@next to see if it works for your case.

**Comment by aitboudad** [comment]
I'm sure I clearly understood the request, just a guess have you tried passing `[null]` as default value:

```json
"type": "array",
"default": [null],
```

**Comment by aitboudad** [comment]
also `minItems` can be useful:

```json
"type": "array",
"default": [null],
"minItems": 1,
```

**Comment by kenisteward** [comment]
> also `minItems` can be useful:
> 
> ```json
> "type": "array",
> "default": [null],
> "minItems": 1,
> ```

@aitboudad I think they want empty arrays to be represented by an empty value ( null / undefined ) instead of the empty array itself.

That should be fixed with the default value changes on v6 right?

**Comment by aitboudad** [comment]
> That should be fixed with the default value changes on v6 right?

Who knows 😄!

**Comment by aitboudad** [comment]
@linfanxxxx could you please apply the following changes and let me know if that fix your issue:

```ts
export class ArrayTypeComponent extends FieldArrayType {
  defaultOptions = {
    defaultValue: null,
  }
}
```

**Comment by adelinor** [comment]
Hi @aitboudad , I tried the option above on the `RepeatTypeComponent` from the [Repeating section example](https://formly.dev/docs/examples/advanced/repeating-section) and the model still gets populated with an empty array.

**Comment by adelinor** [comment]
Dear @linfanxxxx ,

I found a way to set null (or undefined) instead of keeping an empty array :)
In the component that inherits from `FieldArrayType`, redefine the remove method as:

```js
  remove(i: number, { markAsDirty } = { markAsDirty: true }) {
    super.remove(i, { markAsDirty });
    if (this.model && this.model.length === 0) {
      assignFieldValue(this.field, null);
    }
  }
```
See illustration on [stackblitz.com](https://stackblitz.com/edit/angular-formly-repeat-section?file=src%2Fapp%2Fformly-custom-field-array.type.ts) : that example sets `undefined` instead of `null`.

Kind regards
