### ISSUE TITLE
Access Model names for calculated fields with key names containing dot(.)

### ISSUE THREAD

**Issue by saswatpatro** [ngx-formly/ngx-formly#2916]
I have a config json with 3 fields, the 3rd field being a calculated field from data in the previous 2 fields.
Now the catch here is I have dot(.) in their key names. e.g. "something.someone"
When I try rendering the form I get an error showing undefined.
My config_json :
```
{
"fieldGroupClassName": "row",
"fieldGroup": [
{
            "className": "col-2",
            "key": "remarks_backflow.bed",
            "type": "input",
            "templateOptions": {
              "type": "number",
              "label": "Bed",
              "placeholder": "",
              "required": true
            }
          },
{
            "className": "col-2",
            "key": "remarks_backflow.gas",
            "type": "input",
            "templateOptions": {
              "type": "number",
              "label": "Gas",
              "placeholder": "",
              "required": true
            }
          },
{
            "className": "col-2",
            "key": "remarks_backflow.diff",
            "type": "input",
            "templateOptions": {
              "type": "number",
              "label": "Difference",
              "placeholder": "",
              "required": true
            },
            "expressionProperties": {
              "model['remarks_backflow.diff']":"model['remarks_backflow.bed'] - model['remarks_backflow.gas']"
            }
          },
]
}
```

The error is :
FormBuilderComponent.html:24 ERROR TypeError: [Formly Error] [Expression "model['pushin_temperature.kiln_id']"] Cannot set property 'kiln_id']' of undefined
![formlyerror](https://user-images.githubusercontent.com/24622689/125041478-6d753680-e0b6-11eb-9ac7-73106a9365e4.JPG)

**Comment by aitboudad** [comment]
The issue has been fixed in [v5.10.22](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.22) release but better rely on dot notation instead:

```ts
"expressionProperties": {
  "model.remarks_backflow.diff":"model.remarks_backflow.bed - model.remarks_backflow.gas"
}
```

**Comment by saswatpatro** [comment]
Hi @aitboudad Thanks for the fix!
I upgraded my ngx-formly/core version in my Angular 8 app to -
"@ngx-formly/core": "^5.10.22",
"@ngx-formly/bootstrap": "^5.10.22"

And tried the exact expressionProperty json suggested by you above, but I am still getting this error in my console.
![formlyerror](https://user-images.githubusercontent.com/24622689/125206711-45e4c080-e2a6-11eb-9478-b3a971a079f7.JPG)

I have even created a stackblitz where I am facing the same error. Below is a link to it :
[https://stackblitz.com/edit/angular-ujghcq?file=src/app/app.component.ts](url)

**Comment by kenisteward** [comment]
Could you update the link? I'm currently unable to open it.

Also it looks like this is an error I'm the expression not the setting of
the value when I read the error.

Are you perhaps trying to access .bed on a value that is undefined?

**Comment by kenisteward** [comment]
Yeah I'm seeing an update from "cannot set "(formly issue) to "cannot read"
( usually an expression issue )

**Comment by saswatpatro** [comment]
Hi @kenisteward, Below I have given an updated link for the stackblitz code.
[https://stackblitz.com/edit/angular-formly1996](url)

**Comment by kenisteward** [comment]
Yeah your expression is incorrect. It is telling JavaScript to go to a bed key on remarks_backflow object


Change your actual expression string to use

model["remarks_backflow.bed"] 

and the like. And let me know how that goes.  That's what the pr allows for.

I would also highly suggest creating a model that doesn't cause this type of confusion.

I think that's what @aitboudad  was suggesting as well.

**Comment by saswatpatro** [comment]
Thanks @kenisteward for the suggestion, But even if the error in console goes away with your approach it doesn't still solve my requirement of getting the 3rd calculated field by the previous 2 fields.
In the stackblitz link you can still see the Difference field doesn't show me the output even if I have entered valid numbers for bed and gas fields.
I had actually used this approach before, but @aitboudad suggested me using dot notation rather than square brackets in one of the above comments.
Creating a model is a bit difficult in this particular case as I am dynamically generating the fields of the forms according to user requirement.

**Comment by kenisteward** [comment]
![Screenshot_20210712-013113.png](https://user-images.githubusercontent.com/12831669/125241361-f35cd180-e2b0-11eb-8f23-65d0b5fee703.png)

When the data is filled because of your key names the underlying model that is made is an object with fields in them. THis is how angular form fields work.

As long as you are okay with that model then you just need to make sure remarks_backflow is initialized or check to make sure it exists in your expression

E.g. initialize your model with 
{ remarks_backflow: {} }

Or add an expression that sets that key on the model if it doesn't exist.


I would update the stackblitz but it's hard to on my phone.

**Comment by kenisteward** [comment]
@saswatpatro 

https://stackblitz.com/edit/angular-formly1996-mbp7vf?file=src/app/app.component.ts

I was able to get it updated with my proposed example

**Comment by saswatpatro** [comment]
This was of great help @kenisteward . Thanks for the stackblitz!
I had one last doubt, The initialization of json you did inside the model was in relation to the key names I gave to different fields in the form. Now if I have to render this same form using the form json and this time the key structure is same(i.e. it contains dots) but that is generated dynamically(I have no idea what the key names can be, but the structure is same i.e. "something.something").
How should I handle this situation with the calculated field?

**Comment by kenisteward** [comment]
Create an expression property on at least one of the fields that has that object that will set model.theobjname to {} if it doesn't exist the same way you have the other model expression properties.

**Comment by saswatpatro** [comment]
Thanks for the solution along with constant support @kenisteward 
What I tried was adding defaultValue as 0 for the calculated field which even removed the error as well as now the calculated field works as required.
Below I am posting a stackblitz for the solution :
https://stackblitz.com/edit/angular-formly1996

**Comment by kenisteward** [comment]
Yeah that makes sense as it will make sure that the parent object created.
